### ISSUE TITLE
Is it possible to extract attestation key?

### ISSUE THREAD

**Issue by ValentinLiu15** [shakevsky/keybuster#7]
Attestation key is used for Android Hardware Attestation. The certificate is signed by Google and the key is protected by TEE.

**Comment by ValentinLiu15** [comment]
nwd_attest_key

**Comment by ghost** [comment]
Did you get it?

**Comment by ValentinLiu15** [comment]
> Did you get it?

No. Actually, there is another way to extract key just need a rooted Android device.
